services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    mem_limit: 2GB
    working_dir: /app
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    env_file:
      - ./backend/.env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    mem_limit: 256MB
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT} 
    env_file:
      - ./frontend/.env